name: check secrets

on:
  workflow_dispatch:
    inputs:
      copy-changes:
        description: 'Check secrets'

jobs:
  copy-changes:
    runs-on: ubuntu-latest

    steps:
     - name: chech AWS credentials from secrets
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LOL_TEST: ROFL
       run: |
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          echo $LOL_TEST
